---

# The steps within the comments can be effectively replaced by 'module load Nextflow'
# Currently the module has problems being automatically initialized
###

- name: Create NextFlow directory
  file:
    path: "{{ nextflow_dest }}"
    state: directory

- name: Create NextFlow installation subdirectory
  file:
    path: "{{ nextflow_dest }}/workfiles"
    state: directory

- name: Download NextFlow
  get_url:
    url: "{{ nextflow_download_url }}"
    dest: "{{ nextflow_dest }}/nextflow"
    mode: u=rwx

# Resolved any problems. Run-time files are pushed to scratch
- name: Install NextFlow
  shell: "./nextflow"
  environment: "{{ nextflow_env }}"
  args:
    chdir: "{{ nextflow_dest }}"

