---

- name: "Get list of conda environments"
  shell: "conda env list"
  register: py_venv_exists

- name: Setup virtual env and install dependencies
  shell: "conda create -n {{ NGI_venv_name }} pip python=2.7"
  when: not NGI_venv_name in py_venv_exists.stdout|split

- name: Setup virtual env with python3 and install dependencies
  shell: "conda create -n {{ NGI_venv_py3_name }} -c anaconda python=3.8"
  when: not NGI_venv_py3_name in py_venv_exists.stdout|split

- name: Fetch ngi_pipeline from github
  git:
    repo: "{{ ngi_pipeline_repo }}"
    dest: "{{ ngi_pipeline_dest }}"
    version: "{{ ngi_pipeline_version }}"
    force: yes

- name: (Temporary until everything is updated) Install click7.0 as click7.1 breaks everything
  pip:
    name: click
    version: "7.0"
    executable: "{{ ngi_pipeline_venv }}/bin/pip"

- name: Install ngi_pipeline requirements
  pip:
    requirements: "{{ ngi_pipeline_dest }}/requirements.txt"
    executable: "{{ ngi_pipeline_venv }}/bin/pip"

- name: Install ngi_pipeline
  pip:
    name: "file:{{ ngi_pipeline_dest }}"
    executable: "{{ ngi_pipeline_venv }}/bin/pip"

- name: Store ngi_pipeline version in deployment
  lineinfile:
    dest: "{{ deployed_tool_versions }}"
    line: "NGI Pipeline: {{ ngi_pipeline_version }}"

- name: Install PyVCF for joint calling
  pip:
    name: "PyVCF"
    executable: "{{ ngi_pipeline_venv }}/bin/pip"

- name: Create ngi_resources folder
  file:
    name: "{{ ngi_resources }}"
    state: directory

- name: Create ngi_resources/piper folder
  file:
    name: "{{ ngi_resources }}/piper"
    state: directory

- name: Create deployed tools version file
  copy:
    dest: "{{ deployed_tool_versions }}"
    content: "-- {{ deployment_environment }} ({{ deployment_version }}) --"

- name: Deploy GATK license key
  copy:
    src: files/{{ gatk_key }}
    dest: "{{ ngi_resources }}/piper/{{ gatk_key }}"
  ignore_errors: true

- name: Deploy fastqc conf for miarka
  template:
    src: fastq_screen.miarka.conf.j2
    dest: "{{ ngi_pipeline_conf }}/fastq_screen.miarka.conf"

- name: Deploy script for creating site specific ngi_pipeline dirs for logs and db
  template:
    src: create_ngi_pipeline_dirs.sh.j2
    dest: "{{ ngi_resources }}/create_ngi_pipeline_dirs.sh"

- name: Create ngi_pipeline wildwest directory
  file:
    path: "{{ proj_root }}"
    state: directory
  when: deployment_environment in ["staging", "devel"]

- name: Deploy miarka ngi_pipeline config for {{ site }}
  template:
    src: miarka_ngi_config.yaml.j2
    dest: "{{ ngi_pipeline_conf }}/{{ ngi_pipeline_config }}"

- include_tasks: configuration.yml
