- name: create virtual python env for delivery
  shell: conda create --name {{ delivery_env_name }} python=2.7
  args: 
    creates: "{{ delivery_env_path }}"

- name: get delivery from git
  git:
    repo: "{{ delivery_repo }}"
    dest: "{{ delivery_dest }}"
    version: "{{ delivery_version }}"

- name: install delivery requirements
  pip:
    executable: "{{ delivery_env_path }}/bin/pip"
    requirements: "{{ delivery_dest }}/requirements.txt"
    extra_args: "-U"
    state: present

- name: install delivery into venv
  copy:
    src: "{{ delivery_dest }}/deliver.py"
    dest: "{{ delivery_env_path }}/bin/"

- name: ensure conf dir exists
  file:
    path: "{{ ngi_pipeline_conf }}"
    state: directory

- name: deploy ugc bash env file 
  template:
    src: sourceme_ugc.sh.j2
    dest: "{{ ngi_pipeline_conf }}/sourceme_ugc.sh"

- name: try to get delivery commit version
  command: git rev-parse HEAD
  args:
    chdir: "{{ delivery_dest }}"
  register: delivery_version
  ignore_errors: true

- name: store delivery tool version in deployment
  lineinfile:
    dest: "{{ deployed_tool_versions }}"
    line: "delivery: {{ delivery_version.stdout }}"
  when: delivery_version.stdout
